# Generated by Django 5.0.4 on 2024-10-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Data',
            new_name='Date',
        ),
    ]
