# Generated by Django 5.0.4 on 2024-10-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_data_registration_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
