# Generated by Django 5.0.4 on 2024-10-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0005_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('pswd', models.CharField(max_length=100)),
                ('roll', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=50)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
