# Generated by Django 5.0.4 on 2024-10-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_addinquiry_inquirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='addinquiry',
            name='call_done',
            field=models.BooleanField(default=False),
        ),
    ]
